/**
 * Proof Sheet Data - Complete key definitions for visual key inspection
 * Includes ALL keycodes organized by category
 */

import { KeyboardInfo, KeyContent } from "@/types/vial.types";
import { getKeyContents } from "@/utils/keys";

/**
 * Mock KeyboardInfo with cosmetic layer names, sample macros, and tapdances
 * Used for rendering proof sheet keys without a connected keyboard
 */
export const mockKeyboardInfo: KeyboardInfo = {
    rows: 4,
    cols: 12,
    layers: 16,
    cosmetic: {
        name: "Proof Sheet Mock",
        layer: {
            "0": "default",
            "1": "nav",
            "2": "num",
            "3": "sym",
            "4": "fn",
            "5": "mouse",
            "15": "admin",
        },
    },
    macros: [
        { mid: 0, actions: [["text", "Hello"]] },
        { mid: 1, actions: [["tap", "KC_LCTRL"], ["tap", "KC_C"]] },
        { mid: 2, actions: [["text", "World"]] },
        { mid: 3, actions: [["tap", "KC_LALT"], ["tap", "KC_TAB"]] },
        { mid: 15, actions: [["text", "Macro15"]] },
    ],
    tapdances: [
        { idx: 0, tap: "KC_A", hold: "KC_LSHIFT", doubletap: "KC_CAPSLOCK", taphold: "KC_NO", tapping_term: 200 },
        { idx: 1, tap: "KC_SPACE", hold: "MO(1)", doubletap: "KC_ENTER", taphold: "KC_NO", tapping_term: 200 },
        { idx: 2, tap: "KC_ESCAPE", hold: "KC_LCTRL", doubletap: "KC_GRAVE", taphold: "KC_NO", tapping_term: 200 },
    ],
    custom_keycodes: [
        { name: "SV_LEFT_DPI_INC", title: "Left DPI Increase", shortName: "L DPI+" },
        { name: "SV_LEFT_DPI_DEC", title: "Left DPI Decrease", shortName: "L DPI-" },
        { name: "SV_RIGHT_DPI_INC", title: "Right DPI Increase", shortName: "R DPI+" },
        { name: "SV_RIGHT_DPI_DEC", title: "Right DPI Decrease", shortName: "R DPI-" },
        { name: "SV_LEFT_SCROLL_TOGGLE", title: "Left Scroll Toggle", shortName: "L Scrl\nTgl" },
        { name: "SV_RIGHT_SCROLL_TOGGLE", title: "Right Scroll Toggle", shortName: "R Scrl\nTgl" },
        { name: "SV_RECALIBRATE_POINTER", title: "Recalibrate Pointer", shortName: "Recal\nPtr" },
        { name: "SV_MH_CHANGE_TIMEOUTS", title: "Change MH Timeouts", shortName: "MH\nTimeout" },
        { name: "SV_CAPS_WORD", title: "Caps Word", shortName: "Caps\nWord" },
        { name: "SV_TOGGLE_ACHORDION", title: "Toggle Achordion", shortName: "Achord\nTgl" },
        { name: "SV_TOGGLE_23_67", title: "Toggle 2-3 / 6-7", shortName: "Tgl\n23/67" },
        { name: "SV_TOGGLE_45_67", title: "Toggle 4-5 / 6-7", shortName: "Tgl\n45/67" },
        { name: "SV_SNIPER_2", title: "Sniper 2x", shortName: "Sniper\n2x" },
        { name: "SV_SNIPER_3", title: "Sniper 3x", shortName: "Sniper\n3x" },
        { name: "SV_SNIPER_5", title: "Sniper 5x", shortName: "Sniper\n5x" },
        { name: "SV_SNIPER_2_TG", title: "Sniper 2x Toggle", shortName: "Sniper\n2xTG" },
        { name: "SV_SNIPER_3_TG", title: "Sniper 3x Toggle", shortName: "Sniper\n3xTG" },
        { name: "SV_SNIPER_5_TG", title: "Sniper 5x Toggle", shortName: "Sniper\n5xTG" },
        { name: "SV_SCROLL_HOLD", title: "Scroll Hold", shortName: "Scroll\nHold" },
        { name: "SV_SCROLL_TOGGLE", title: "Scroll Toggle", shortName: "Scroll\nTgl" },
        { name: "SV_OUTPUT_STATUS", title: "Output Status", shortName: "Output\nStatus" },
        { name: "SV_NATURAL_SCROLL_TOGGLE", title: "Natural Scroll Toggle", shortName: "Nat Scrl\nTgl" },
        { name: "SV_BOOST_2", title: "Boost 2x", shortName: "Boost\n2x" },
        { name: "SV_BOOST_3", title: "Boost 3x", shortName: "Boost\n3x" },
        { name: "SV_BOOST_5", title: "Boost 5x", shortName: "Boost\n5x" },
        { name: "SV_BOOST_2_TG", title: "Boost 2x Toggle", shortName: "Boost\n2xTG" },
        { name: "SV_BOOST_3_TG", title: "Boost 3x Toggle", shortName: "Boost\n3xTG" },
        { name: "SV_BOOST_5_TG", title: "Boost 5x Toggle", shortName: "Boost\n5xTG" },
    ],
};

/**
 * Proof category definition
 */
export interface ProofKey {
    keycode: string;
    description?: string;
}

export interface ProofCategory {
    name: string;
    description: string;
    keys: ProofKey[];
}

/**
 * All proof categories with ALL keys
 */
export const proofCategories: ProofCategory[] = [
    {
        name: "Special Keys",
        description: "Blank and transparent keys",
        keys: [
            { keycode: "KC_NO", description: "No key (blank)" },
            { keycode: "KC_TRNS", description: "Transparent (pass-through)" },
        ],
    },
    {
        name: "Letters",
        description: "All letter keys A-Z",
        keys: [
            { keycode: "KC_A" }, { keycode: "KC_B" }, { keycode: "KC_C" }, { keycode: "KC_D" },
            { keycode: "KC_E" }, { keycode: "KC_F" }, { keycode: "KC_G" }, { keycode: "KC_H" },
            { keycode: "KC_I" }, { keycode: "KC_J" }, { keycode: "KC_K" }, { keycode: "KC_L" },
            { keycode: "KC_M" }, { keycode: "KC_N" }, { keycode: "KC_O" }, { keycode: "KC_P" },
            { keycode: "KC_Q" }, { keycode: "KC_R" }, { keycode: "KC_S" }, { keycode: "KC_T" },
            { keycode: "KC_U" }, { keycode: "KC_V" }, { keycode: "KC_W" }, { keycode: "KC_X" },
            { keycode: "KC_Y" }, { keycode: "KC_Z" },
        ],
    },
    {
        name: "Numbers",
        description: "Number keys 0-9 (show shift symbols)",
        keys: [
            { keycode: "KC_1", description: "!/1" }, { keycode: "KC_2", description: "@/2" },
            { keycode: "KC_3", description: "#/3" }, { keycode: "KC_4", description: "$/4" },
            { keycode: "KC_5", description: "%/5" }, { keycode: "KC_6", description: "^/6" },
            { keycode: "KC_7", description: "&/7" }, { keycode: "KC_8", description: "*/8" },
            { keycode: "KC_9", description: "(/9" }, { keycode: "KC_0", description: ")/0" },
        ],
    },
    {
        name: "Punctuation",
        description: "Punctuation and symbol keys",
        keys: [
            { keycode: "KC_MINUS", description: "- / _" },
            { keycode: "KC_EQUAL", description: "= / +" },
            { keycode: "KC_LBRACKET", description: "[ / {" },
            { keycode: "KC_RBRACKET", description: "] / }" },
            { keycode: "KC_BSLASH", description: "\\ / |" },
            { keycode: "KC_SCOLON", description: "; / :" },
            { keycode: "KC_QUOTE", description: "' / \"" },
            { keycode: "KC_GRAVE", description: "` / ~" },
            { keycode: "KC_COMMA", description: ", / <" },
            { keycode: "KC_DOT", description: ". / >" },
            { keycode: "KC_SLASH", description: "/ / ?" },
            { keycode: "KC_NONUS_HASH", description: "Non-US #" },
            { keycode: "KC_NONUS_BSLASH", description: "Non-US \\" },
        ],
    },
    {
        name: "Shifted Symbols",
        description: "Pre-shifted symbol keycodes",
        keys: [
            { keycode: "KC_EXLM", description: "!" },
            { keycode: "KC_AT", description: "@" },
            { keycode: "KC_HASH", description: "#" },
            { keycode: "KC_DLR", description: "$" },
            { keycode: "KC_PERC", description: "%" },
            { keycode: "KC_CIRC", description: "^" },
            { keycode: "KC_AMPR", description: "&" },
            { keycode: "KC_ASTR", description: "*" },
            { keycode: "KC_LPRN", description: "(" },
            { keycode: "KC_RPRN", description: ")" },
            { keycode: "KC_UNDS", description: "_" },
            { keycode: "KC_PLUS", description: "+" },
            { keycode: "KC_LCBR", description: "{" },
            { keycode: "KC_RCBR", description: "}" },
            { keycode: "KC_PIPE", description: "|" },
            { keycode: "KC_COLN", description: ":" },
            { keycode: "KC_DQUO", description: "\"" },
            { keycode: "KC_TILD", description: "~" },
            { keycode: "KC_LT", description: "<" },
            { keycode: "KC_GT", description: ">" },
            { keycode: "KC_QUES", description: "?" },
        ],
    },
    {
        name: "Editing Keys",
        description: "Common editing and control keys",
        keys: [
            { keycode: "KC_ENTER", description: "Enter/Return" },
            { keycode: "KC_ESCAPE", description: "Escape" },
            { keycode: "KC_BSPACE", description: "Backspace" },
            { keycode: "KC_TAB", description: "Tab" },
            { keycode: "KC_SPACE", description: "Space" },
            { keycode: "KC_CAPSLOCK", description: "Caps Lock" },
            { keycode: "KC_INSERT", description: "Insert" },
            { keycode: "KC_DELETE", description: "Delete" },
            { keycode: "KC_APPLICATION", description: "Application/Menu" },
        ],
    },
    {
        name: "Modifiers",
        description: "All modifier keys (Ctrl, Shift, Alt, GUI)",
        keys: [
            { keycode: "KC_LCTRL", description: "Left Control" },
            { keycode: "KC_LSHIFT", description: "Left Shift" },
            { keycode: "KC_LALT", description: "Left Alt" },
            { keycode: "KC_LGUI", description: "Left GUI/Super" },
            { keycode: "KC_RCTRL", description: "Right Control" },
            { keycode: "KC_RSHIFT", description: "Right Shift" },
            { keycode: "KC_RALT", description: "Right Alt" },
            { keycode: "KC_RGUI", description: "Right GUI/Super" },
        ],
    },
    {
        name: "Function Keys",
        description: "F1-F24 function keys",
        keys: [
            { keycode: "KC_F1" }, { keycode: "KC_F2" }, { keycode: "KC_F3" }, { keycode: "KC_F4" },
            { keycode: "KC_F5" }, { keycode: "KC_F6" }, { keycode: "KC_F7" }, { keycode: "KC_F8" },
            { keycode: "KC_F9" }, { keycode: "KC_F10" }, { keycode: "KC_F11" }, { keycode: "KC_F12" },
            { keycode: "KC_F13" }, { keycode: "KC_F14" }, { keycode: "KC_F15" }, { keycode: "KC_F16" },
            { keycode: "KC_F17" }, { keycode: "KC_F18" }, { keycode: "KC_F19" }, { keycode: "KC_F20" },
            { keycode: "KC_F21" }, { keycode: "KC_F22" }, { keycode: "KC_F23" }, { keycode: "KC_F24" },
        ],
    },
    {
        name: "Navigation",
        description: "Arrow keys and navigation cluster",
        keys: [
            { keycode: "KC_UP", description: "Up Arrow" },
            { keycode: "KC_DOWN", description: "Down Arrow" },
            { keycode: "KC_LEFT", description: "Left Arrow" },
            { keycode: "KC_RIGHT", description: "Right Arrow" },
            { keycode: "KC_HOME", description: "Home" },
            { keycode: "KC_END", description: "End" },
            { keycode: "KC_PGUP", description: "Page Up" },
            { keycode: "KC_PGDOWN", description: "Page Down" },
            { keycode: "KC_PSCREEN", description: "Print Screen" },
            { keycode: "KC_SCROLLLOCK", description: "Scroll Lock" },
            { keycode: "KC_PAUSE", description: "Pause/Break" },
        ],
    },
    {
        name: "Numpad",
        description: "Numeric keypad keys",
        keys: [
            { keycode: "KC_NUMLOCK", description: "Num Lock" },
            { keycode: "KC_KP_SLASH", description: "Numpad /" },
            { keycode: "KC_KP_ASTERISK", description: "Numpad *" },
            { keycode: "KC_KP_MINUS", description: "Numpad -" },
            { keycode: "KC_KP_PLUS", description: "Numpad +" },
            { keycode: "KC_KP_ENTER", description: "Numpad Enter" },
            { keycode: "KC_KP_1" }, { keycode: "KC_KP_2" }, { keycode: "KC_KP_3" },
            { keycode: "KC_KP_4" }, { keycode: "KC_KP_5" }, { keycode: "KC_KP_6" },
            { keycode: "KC_KP_7" }, { keycode: "KC_KP_8" }, { keycode: "KC_KP_9" },
            { keycode: "KC_KP_0" },
            { keycode: "KC_KP_DOT", description: "Numpad ." },
            { keycode: "KC_KP_EQUAL", description: "Numpad =" },
            { keycode: "KC_KP_COMMA", description: "Numpad ," },
        ],
    },
    {
        name: "Media Keys",
        description: "Media playback and volume controls",
        keys: [
            { keycode: "KC_MUTE", description: "Mute" },
            { keycode: "KC_VOLU", description: "Volume Up" },
            { keycode: "KC_VOLD", description: "Volume Down" },
            { keycode: "KC_MPLY", description: "Play/Pause" },
            { keycode: "KC_MSTP", description: "Stop" },
            { keycode: "KC_MNXT", description: "Next Track" },
            { keycode: "KC_MPRV", description: "Previous Track" },
            { keycode: "KC_MFFD", description: "Fast Forward" },
            { keycode: "KC_MRWD", description: "Rewind" },
            { keycode: "KC_MSEL", description: "Media Select" },
            { keycode: "KC_EJCT", description: "Eject" },
        ],
    },
    {
        name: "System Keys",
        description: "System and application control",
        keys: [
            { keycode: "KC_PWR", description: "Power" },
            { keycode: "KC_SLEP", description: "Sleep" },
            { keycode: "KC_WAKE", description: "Wake" },
            { keycode: "KC_BRIU", description: "Brightness Up" },
            { keycode: "KC_BRID", description: "Brightness Down" },
            { keycode: "KC_MAIL", description: "Mail" },
            { keycode: "KC_CALC", description: "Calculator" },
            { keycode: "KC_MYCM", description: "My Computer" },
            { keycode: "KC_WSCH", description: "Web Search" },
            { keycode: "KC_WHOM", description: "Web Home" },
            { keycode: "KC_WBAK", description: "Web Back" },
            { keycode: "KC_WFWD", description: "Web Forward" },
            { keycode: "KC_WSTP", description: "Web Stop" },
            { keycode: "KC_WREF", description: "Web Refresh" },
            { keycode: "KC_WFAV", description: "Web Favorites" },
        ],
    },
    {
        name: "Mouse Movement",
        description: "Mouse cursor movement keys",
        keys: [
            { keycode: "KC_MS_U", description: "Mouse Up" },
            { keycode: "KC_MS_D", description: "Mouse Down" },
            { keycode: "KC_MS_L", description: "Mouse Left" },
            { keycode: "KC_MS_R", description: "Mouse Right" },
        ],
    },
    {
        name: "Mouse Wheel",
        description: "Mouse wheel scroll keys",
        keys: [
            { keycode: "KC_WH_U", description: "Wheel Up" },
            { keycode: "KC_WH_D", description: "Wheel Down" },
            { keycode: "KC_WH_L", description: "Wheel Left" },
            { keycode: "KC_WH_R", description: "Wheel Right" },
        ],
    },
    {
        name: "Mouse Buttons",
        description: "Mouse button clicks",
        keys: [
            { keycode: "KC_BTN1", description: "Button 1 (Left)" },
            { keycode: "KC_BTN2", description: "Button 2 (Right)" },
            { keycode: "KC_BTN3", description: "Button 3 (Middle)" },
            { keycode: "KC_BTN4", description: "Button 4" },
            { keycode: "KC_BTN5", description: "Button 5" },
            { keycode: "KC_MS_BTN6", description: "Button 6" },
            { keycode: "KC_MS_BTN7", description: "Button 7" },
            { keycode: "KC_MS_BTN8", description: "Button 8" },
        ],
    },
    {
        name: "Mouse Acceleration",
        description: "Mouse acceleration controls",
        keys: [
            { keycode: "KC_ACL0", description: "Acceleration 0" },
            { keycode: "KC_ACL1", description: "Acceleration 1" },
            { keycode: "KC_ACL2", description: "Acceleration 2" },
        ],
    },
    {
        name: "Layer Keys (MO)",
        description: "Momentary layer activation (0-15)",
        keys: [
            { keycode: "MO(0)" }, { keycode: "MO(1)" }, { keycode: "MO(2)" }, { keycode: "MO(3)" },
            { keycode: "MO(4)" }, { keycode: "MO(5)" }, { keycode: "MO(6)" }, { keycode: "MO(7)" },
            { keycode: "MO(8)" }, { keycode: "MO(9)" }, { keycode: "MO(10)" }, { keycode: "MO(11)" },
            { keycode: "MO(12)" }, { keycode: "MO(13)" }, { keycode: "MO(14)" }, { keycode: "MO(15)" },
        ],
    },
    {
        name: "Layer Keys (DF)",
        description: "Default layer switch (0-15)",
        keys: [
            { keycode: "DF(0)" }, { keycode: "DF(1)" }, { keycode: "DF(2)" }, { keycode: "DF(3)" },
            { keycode: "DF(4)" }, { keycode: "DF(5)" }, { keycode: "DF(6)" }, { keycode: "DF(7)" },
            { keycode: "DF(8)" }, { keycode: "DF(9)" }, { keycode: "DF(10)" }, { keycode: "DF(11)" },
            { keycode: "DF(12)" }, { keycode: "DF(13)" }, { keycode: "DF(14)" }, { keycode: "DF(15)" },
        ],
    },
    {
        name: "Layer Keys (TG)",
        description: "Toggle layer (0-15)",
        keys: [
            { keycode: "TG(0)" }, { keycode: "TG(1)" }, { keycode: "TG(2)" }, { keycode: "TG(3)" },
            { keycode: "TG(4)" }, { keycode: "TG(5)" }, { keycode: "TG(6)" }, { keycode: "TG(7)" },
            { keycode: "TG(8)" }, { keycode: "TG(9)" }, { keycode: "TG(10)" }, { keycode: "TG(11)" },
            { keycode: "TG(12)" }, { keycode: "TG(13)" }, { keycode: "TG(14)" }, { keycode: "TG(15)" },
        ],
    },
    {
        name: "Layer Keys (TT)",
        description: "Tap-toggle layer (0-15)",
        keys: [
            { keycode: "TT(0)" }, { keycode: "TT(1)" }, { keycode: "TT(2)" }, { keycode: "TT(3)" },
            { keycode: "TT(4)" }, { keycode: "TT(5)" }, { keycode: "TT(6)" }, { keycode: "TT(7)" },
            { keycode: "TT(8)" }, { keycode: "TT(9)" }, { keycode: "TT(10)" }, { keycode: "TT(11)" },
            { keycode: "TT(12)" }, { keycode: "TT(13)" }, { keycode: "TT(14)" }, { keycode: "TT(15)" },
        ],
    },
    {
        name: "Layer Keys (OSL)",
        description: "One-shot layer (0-15)",
        keys: [
            { keycode: "OSL(0)" }, { keycode: "OSL(1)" }, { keycode: "OSL(2)" }, { keycode: "OSL(3)" },
            { keycode: "OSL(4)" }, { keycode: "OSL(5)" }, { keycode: "OSL(6)" }, { keycode: "OSL(7)" },
            { keycode: "OSL(8)" }, { keycode: "OSL(9)" }, { keycode: "OSL(10)" }, { keycode: "OSL(11)" },
            { keycode: "OSL(12)" }, { keycode: "OSL(13)" }, { keycode: "OSL(14)" }, { keycode: "OSL(15)" },
        ],
    },
    {
        name: "Layer Keys (TO)",
        description: "Turn on layer (0-15)",
        keys: [
            { keycode: "TO(0)" }, { keycode: "TO(1)" }, { keycode: "TO(2)" }, { keycode: "TO(3)" },
            { keycode: "TO(4)" }, { keycode: "TO(5)" }, { keycode: "TO(6)" }, { keycode: "TO(7)" },
            { keycode: "TO(8)" }, { keycode: "TO(9)" }, { keycode: "TO(10)" }, { keycode: "TO(11)" },
            { keycode: "TO(12)" }, { keycode: "TO(13)" }, { keycode: "TO(14)" }, { keycode: "TO(15)" },
        ],
    },
    {
        name: "Layer Tap (LT)",
        description: "Layer on hold, key on tap (0-15)",
        keys: [
            { keycode: "LT0(KC_SPACE)", description: "LT0 / Space" },
            { keycode: "LT1(KC_SPACE)", description: "LT1 / Space" },
            { keycode: "LT2(KC_SPACE)", description: "LT2 / Space" },
            { keycode: "LT3(KC_SPACE)", description: "LT3 / Space" },
            { keycode: "LT4(KC_BSPACE)", description: "LT4 / Backspace" },
            { keycode: "LT5(KC_ENTER)", description: "LT5 / Enter" },
            { keycode: "LT6(KC_TAB)", description: "LT6 / Tab" },
            { keycode: "LT7(KC_ESCAPE)", description: "LT7 / Escape" },
            { keycode: "LT8(KC_A)", description: "LT8 / A" },
            { keycode: "LT9(KC_NO)", description: "LT9 / No tap" },
            { keycode: "LT10(KC_SPACE)", description: "LT10 / Space" },
            { keycode: "LT11(KC_SPACE)", description: "LT11 / Space" },
            { keycode: "LT12(KC_SPACE)", description: "LT12 / Space" },
            { keycode: "LT13(KC_SPACE)", description: "LT13 / Space" },
            { keycode: "LT14(KC_SPACE)", description: "LT14 / Space" },
            { keycode: "LT15(KC_SPACE)", description: "LT15 / Space" },
        ],
    },
    {
        name: "Mod-Tap (Left)",
        description: "Left-side modifier on hold, key on tap",
        keys: [
            { keycode: "LCTL_T(KC_A)", description: "LCtrl / A" },
            { keycode: "LSFT_T(KC_S)", description: "LShift / S" },
            { keycode: "LALT_T(KC_D)", description: "LAlt / D" },
            { keycode: "LGUI_T(KC_F)", description: "LGUI / F" },
            { keycode: "C_S_T(KC_Z)", description: "Ctrl+Shift / Z" },
            { keycode: "LCA_T(KC_X)", description: "Ctrl+Alt / X" },
            { keycode: "LSA_T(KC_C)", description: "Shift+Alt / C" },
            { keycode: "SGUI_T(KC_V)", description: "Shift+GUI / V" },
            { keycode: "LCG_T(KC_B)", description: "Ctrl+GUI / B" },
            { keycode: "LAG_T(KC_N)", description: "Alt+GUI / N" },
            { keycode: "LCAG_T(KC_M)", description: "Ctrl+Alt+GUI / M" },
            { keycode: "MEH_T(KC_TAB)", description: "Meh / Tab" },
            { keycode: "ALL_T(KC_SPACE)", description: "Hyper / Space" },
        ],
    },
    {
        name: "Mod-Tap (Right)",
        description: "Right-side modifier on hold, key on tap",
        keys: [
            { keycode: "RCTL_T(KC_J)", description: "RCtrl / J" },
            { keycode: "RSFT_T(KC_K)", description: "RShift / K" },
            { keycode: "RALT_T(KC_L)", description: "RAlt / L" },
            { keycode: "RGUI_T(KC_SCOLON)", description: "RGUI / ;" },
            { keycode: "RCS_T(KC_N)", description: "RCtrl+Shift / N" },
            { keycode: "RCA_T(KC_M)", description: "RCtrl+Alt / M" },
            { keycode: "RSA_T(KC_COMMA)", description: "RShift+Alt / ," },
            { keycode: "RSG_T(KC_DOT)", description: "RShift+GUI / ." },
            { keycode: "RCG_T(KC_SLASH)", description: "RCtrl+GUI / /" },
            { keycode: "RAG_T(KC_QUOTE)", description: "RAlt+GUI / '" },
            { keycode: "RCAG_T(KC_BSLASH)", description: "RCtrl+Alt+GUI / \\" },
        ],
    },
    {
        name: "Mod-Mask (Left)",
        description: "Left-side modifier + key combinations",
        keys: [
            { keycode: "LCTL(KC_C)", description: "Ctrl+C" },
            { keycode: "LCTL(KC_V)", description: "Ctrl+V" },
            { keycode: "LCTL(KC_X)", description: "Ctrl+X" },
            { keycode: "LCTL(KC_Z)", description: "Ctrl+Z" },
            { keycode: "LCTL(KC_A)", description: "Ctrl+A" },
            { keycode: "LCTL(KC_S)", description: "Ctrl+S" },
            { keycode: "LSFT(KC_INSERT)", description: "Shift+Insert" },
            { keycode: "LALT(KC_F4)", description: "Alt+F4" },
            { keycode: "LGUI(KC_TAB)", description: "GUI+Tab" },
            { keycode: "LGUI(KC_L)", description: "GUI+L" },
            { keycode: "C_S(KC_ESCAPE)", description: "Ctrl+Shift+Esc" },
            { keycode: "LCA(KC_DELETE)", description: "Ctrl+Alt+Del" },
            { keycode: "MEH(KC_A)", description: "Meh+A" },
            { keycode: "HYPR(KC_A)", description: "Hyper+A" },
        ],
    },
    {
        name: "One-Shot Modifiers (Left)",
        description: "Left-side one-shot modifiers",
        keys: [
            { keycode: "OSM(MOD_LCTL)", description: "One-shot LCtrl" },
            { keycode: "OSM(MOD_LSFT)", description: "One-shot LShift" },
            { keycode: "OSM(MOD_LALT)", description: "One-shot LAlt" },
            { keycode: "OSM(MOD_LGUI)", description: "One-shot LGUI" },
            { keycode: "OSM(MOD_LCTL|MOD_LSFT)", description: "One-shot LCtrl+LShift" },
            { keycode: "OSM(MOD_LCTL|MOD_LALT)", description: "One-shot LCtrl+LAlt" },
            { keycode: "OSM(MOD_LCTL|MOD_LGUI)", description: "One-shot LCtrl+LGUI" },
            { keycode: "OSM(MOD_LSFT|MOD_LALT)", description: "One-shot LShift+LAlt" },
            { keycode: "OSM(MOD_LSFT|MOD_LGUI)", description: "One-shot LShift+LGUI" },
            { keycode: "OSM(MOD_LALT|MOD_LGUI)", description: "One-shot LAlt+LGUI" },
            { keycode: "OSM(MOD_MEH)", description: "One-shot Meh" },
            { keycode: "OSM(MOD_HYPR)", description: "One-shot Hyper" },
        ],
    },
    {
        name: "One-Shot Modifiers (Right)",
        description: "Right-side one-shot modifiers",
        keys: [
            { keycode: "OSM(MOD_RCTL)", description: "One-shot RCtrl" },
            { keycode: "OSM(MOD_RSFT)", description: "One-shot RShift" },
            { keycode: "OSM(MOD_RALT)", description: "One-shot RAlt" },
            { keycode: "OSM(MOD_RGUI)", description: "One-shot RGUI" },
            { keycode: "OSM(MOD_RCTL|MOD_RSFT)", description: "One-shot RCtrl+RShift" },
            { keycode: "OSM(MOD_RCTL|MOD_RALT)", description: "One-shot RCtrl+RAlt" },
            { keycode: "OSM(MOD_RCTL|MOD_RGUI)", description: "One-shot RCtrl+RGUI" },
            { keycode: "OSM(MOD_RSFT|MOD_RALT)", description: "One-shot RShift+RAlt" },
            { keycode: "OSM(MOD_RSFT|MOD_RGUI)", description: "One-shot RShift+RGUI" },
            { keycode: "OSM(MOD_RALT|MOD_RGUI)", description: "One-shot RAlt+RGUI" },
        ],
    },
    {
        name: "Macros",
        description: "Macro key assignments (0-15)",
        keys: [
            { keycode: "M0", description: "Macro 0" },
            { keycode: "M1", description: "Macro 1" },
            { keycode: "M2", description: "Macro 2" },
            { keycode: "M3", description: "Macro 3" },
            { keycode: "M4", description: "Macro 4" },
            { keycode: "M5", description: "Macro 5" },
            { keycode: "M6", description: "Macro 6" },
            { keycode: "M7", description: "Macro 7" },
            { keycode: "M8", description: "Macro 8" },
            { keycode: "M9", description: "Macro 9" },
            { keycode: "M10", description: "Macro 10" },
            { keycode: "M11", description: "Macro 11" },
            { keycode: "M12", description: "Macro 12" },
            { keycode: "M13", description: "Macro 13" },
            { keycode: "M14", description: "Macro 14" },
            { keycode: "M15", description: "Macro 15" },
        ],
    },
    {
        name: "Tap Dances",
        description: "Tap dance assignments (0-31)",
        keys: [
            { keycode: "TD(0)" }, { keycode: "TD(1)" }, { keycode: "TD(2)" }, { keycode: "TD(3)" },
            { keycode: "TD(4)" }, { keycode: "TD(5)" }, { keycode: "TD(6)" }, { keycode: "TD(7)" },
            { keycode: "TD(8)" }, { keycode: "TD(9)" }, { keycode: "TD(10)" }, { keycode: "TD(11)" },
            { keycode: "TD(12)" }, { keycode: "TD(13)" }, { keycode: "TD(14)" }, { keycode: "TD(15)" },
            { keycode: "TD(16)" }, { keycode: "TD(17)" }, { keycode: "TD(18)" }, { keycode: "TD(19)" },
            { keycode: "TD(20)" }, { keycode: "TD(21)" }, { keycode: "TD(22)" }, { keycode: "TD(23)" },
            { keycode: "TD(24)" }, { keycode: "TD(25)" }, { keycode: "TD(26)" }, { keycode: "TD(27)" },
            { keycode: "TD(28)" }, { keycode: "TD(29)" }, { keycode: "TD(30)" }, { keycode: "TD(31)" },
        ],
    },
    {
        name: "User/Custom Keycodes (Legacy)",
        description: "Legacy Vial USER keycodes (USER00-USER15)",
        keys: [
            { keycode: "USER00", description: "User keycode 0" },
            { keycode: "USER01", description: "User keycode 1" },
            { keycode: "USER02", description: "User keycode 2" },
            { keycode: "USER03", description: "User keycode 3" },
            { keycode: "USER04", description: "User keycode 4" },
            { keycode: "USER05", description: "User keycode 5" },
            { keycode: "USER06", description: "User keycode 6" },
            { keycode: "USER07", description: "User keycode 7" },
            { keycode: "USER08", description: "User keycode 8" },
            { keycode: "USER09", description: "User keycode 9" },
            { keycode: "USER10", description: "User keycode 10" },
            { keycode: "USER11", description: "User keycode 11" },
            { keycode: "USER12", description: "User keycode 12" },
            { keycode: "USER13", description: "User keycode 13" },
            { keycode: "USER14", description: "User keycode 14" },
            { keycode: "USER15", description: "User keycode 15" },
        ],
    },
    {
        name: "Svalboard Custom Keycodes (QK_USER)",
        description: "QMK/Viable custom keycodes - Svalboard pointing, scroll, sniper, and config keys",
        keys: [
            { keycode: "QK_USER_0", description: "SV Left DPI Increase" },
            { keycode: "QK_USER_1", description: "SV Left DPI Decrease" },
            { keycode: "QK_USER_2", description: "SV Right DPI Increase" },
            { keycode: "QK_USER_3", description: "SV Right DPI Decrease" },
            { keycode: "QK_USER_4", description: "SV Left Scroll Toggle" },
            { keycode: "QK_USER_5", description: "SV Right Scroll Toggle" },
            { keycode: "QK_USER_6", description: "SV Recalibrate Pointer" },
            { keycode: "QK_USER_7", description: "SV MH Change Timeouts" },
            { keycode: "QK_USER_8", description: "SV Caps Word" },
            { keycode: "QK_USER_9", description: "SV Toggle Achordion" },
            { keycode: "QK_USER_10", description: "SV Toggle 2-3 / 6-7" },
            { keycode: "QK_USER_11", description: "SV Toggle 4-5 / 6-7" },
            { keycode: "QK_USER_12", description: "SV Sniper 2x" },
            { keycode: "QK_USER_13", description: "SV Sniper 3x" },
            { keycode: "QK_USER_14", description: "SV Sniper 5x" },
            { keycode: "QK_USER_15", description: "SV Sniper 2x Toggle" },
            { keycode: "QK_USER_16", description: "SV Sniper 3x Toggle" },
            { keycode: "QK_USER_17", description: "SV Sniper 5x Toggle" },
            { keycode: "QK_USER_18", description: "SV Scroll Hold" },
            { keycode: "QK_USER_19", description: "SV Scroll Toggle" },
            { keycode: "QK_USER_20", description: "SV Output Status" },
            { keycode: "QK_USER_21", description: "SV Natural Scroll Toggle" },
            { keycode: "QK_USER_22", description: "QK User 22 (unassigned)" },
            { keycode: "QK_USER_23", description: "QK User 23 (unassigned)" },
            { keycode: "QK_USER_24", description: "QK User 24 (unassigned)" },
            { keycode: "QK_USER_25", description: "QK User 25 (unassigned)" },
            { keycode: "QK_USER_26", description: "QK User 26 (unassigned)" },
            { keycode: "QK_USER_27", description: "QK User 27 (unassigned)" },
            { keycode: "QK_USER_28", description: "QK User 28 (unassigned)" },
            { keycode: "QK_USER_29", description: "QK User 29 (unassigned)" },
            { keycode: "QK_USER_30", description: "QK User 30 (unassigned)" },
            { keycode: "QK_USER_31", description: "QK User 31 (unassigned)" },
        ],
    },
    {
        name: "QMK Special",
        description: "QMK-specific special keycodes",
        keys: [
            { keycode: "QK_REPEAT_KEY", description: "Repeat last key" },
            { keycode: "QK_ALT_REPEAT_KEY", description: "Alternate repeat" },
            { keycode: "QK_LAYER_LOCK", description: "Layer Lock" },
            { keycode: "QK_LEADER", description: "Leader Key" },
            { keycode: "QK_REBOOT", description: "Reboot keyboard" },
            { keycode: "QK_DEBUG_TOGGLE", description: "Toggle debug mode" },
            { keycode: "QK_CLEAR_EEPROM", description: "Clear EEPROM" },
            { keycode: "RESET", description: "Reset to bootloader" },
        ],
    },
    {
        name: "Backlight",
        description: "Backlight control keys",
        keys: [
            { keycode: "BL_ON", description: "Backlight On" },
            { keycode: "BL_OFF", description: "Backlight Off" },
            { keycode: "BL_TOGG", description: "Backlight Toggle" },
            { keycode: "BL_DEC", description: "Backlight Decrease" },
            { keycode: "BL_INC", description: "Backlight Increase" },
            { keycode: "BL_STEP", description: "Backlight Step" },
            { keycode: "BL_BRTG", description: "Backlight Breathing Toggle" },
        ],
    },
    {
        name: "RGB Lighting",
        description: "RGB underglow lighting controls",
        keys: [
            { keycode: "RGB_TOG", description: "RGB Toggle" },
            { keycode: "RGB_MOD", description: "RGB Mode Next" },
            { keycode: "RGB_RMOD", description: "RGB Mode Previous" },
            { keycode: "RGB_HUI", description: "Hue Increase" },
            { keycode: "RGB_HUD", description: "Hue Decrease" },
            { keycode: "RGB_SAI", description: "Saturation Increase" },
            { keycode: "RGB_SAD", description: "Saturation Decrease" },
            { keycode: "RGB_VAI", description: "Value/Brightness Increase" },
            { keycode: "RGB_VAD", description: "Value/Brightness Decrease" },
            { keycode: "RGB_SPI", description: "Speed Increase" },
            { keycode: "RGB_SPD", description: "Speed Decrease" },
            { keycode: "RGB_M_P", description: "Mode: Plain" },
            { keycode: "RGB_M_B", description: "Mode: Breathe" },
            { keycode: "RGB_M_R", description: "Mode: Rainbow" },
            { keycode: "RGB_M_SW", description: "Mode: Swirl" },
            { keycode: "RGB_M_SN", description: "Mode: Snake" },
            { keycode: "RGB_M_K", description: "Mode: Knight" },
            { keycode: "RGB_M_X", description: "Mode: Xmas" },
            { keycode: "RGB_M_G", description: "Mode: Gradient" },
            { keycode: "RGB_M_T", description: "Mode: Test" },
        ],
    },
    {
        name: "LED Matrix",
        description: "LED Matrix control keys",
        keys: [
            { keycode: "QK_LED_MATRIX_ON", description: "LED Matrix On" },
            { keycode: "QK_LED_MATRIX_OFF", description: "LED Matrix Off" },
            { keycode: "QK_LED_MATRIX_TOGGLE", description: "LED Matrix Toggle" },
            { keycode: "QK_LED_MATRIX_MODE_NEXT", description: "Mode Next" },
            { keycode: "QK_LED_MATRIX_MODE_PREVIOUS", description: "Mode Previous" },
            { keycode: "QK_LED_MATRIX_BRIGHTNESS_UP", description: "Brightness Up" },
            { keycode: "QK_LED_MATRIX_BRIGHTNESS_DOWN", description: "Brightness Down" },
            { keycode: "QK_LED_MATRIX_SPEED_UP", description: "Speed Up" },
            { keycode: "QK_LED_MATRIX_SPEED_DOWN", description: "Speed Down" },
        ],
    },
    {
        name: "RGB Matrix",
        description: "RGB Matrix per-key lighting controls",
        keys: [
            { keycode: "QK_RGB_MATRIX_ON", description: "RGB Matrix On" },
            { keycode: "QK_RGB_MATRIX_OFF", description: "RGB Matrix Off" },
            { keycode: "QK_RGB_MATRIX_TOGGLE", description: "RGB Matrix Toggle" },
            { keycode: "QK_RGB_MATRIX_MODE_NEXT", description: "Mode Next" },
            { keycode: "QK_RGB_MATRIX_MODE_PREVIOUS", description: "Mode Previous" },
            { keycode: "QK_RGB_MATRIX_HUE_UP", description: "Hue Up" },
            { keycode: "QK_RGB_MATRIX_HUE_DOWN", description: "Hue Down" },
            { keycode: "QK_RGB_MATRIX_SATURATION_UP", description: "Saturation Up" },
            { keycode: "QK_RGB_MATRIX_SATURATION_DOWN", description: "Saturation Down" },
            { keycode: "QK_RGB_MATRIX_VALUE_UP", description: "Brightness Up" },
            { keycode: "QK_RGB_MATRIX_VALUE_DOWN", description: "Brightness Down" },
            { keycode: "QK_RGB_MATRIX_SPEED_UP", description: "Speed Up" },
            { keycode: "QK_RGB_MATRIX_SPEED_DOWN", description: "Speed Down" },
        ],
    },
    {
        name: "Audio & Music",
        description: "Audio and music mode controls",
        keys: [
            { keycode: "AU_ON", description: "Audio On" },
            { keycode: "AU_OFF", description: "Audio Off" },
            { keycode: "AU_TOG", description: "Audio Toggle" },
            { keycode: "MU_ON", description: "Music On" },
            { keycode: "MU_OFF", description: "Music Off" },
            { keycode: "MU_TOG", description: "Music Toggle" },
            { keycode: "MU_MOD", description: "Music Mode" },
            { keycode: "CLICKY_TOGGLE", description: "Clicky Toggle" },
            { keycode: "CLICKY_UP", description: "Clicky Frequency Up" },
            { keycode: "CLICKY_DOWN", description: "Clicky Frequency Down" },
            { keycode: "CLICKY_RESET", description: "Clicky Frequency Reset" },
        ],
    },
    {
        name: "Haptic Feedback",
        description: "Haptic feedback controls",
        keys: [
            { keycode: "HPT_ON", description: "Haptic On" },
            { keycode: "HPT_OFF", description: "Haptic Off" },
            { keycode: "HPT_TOG", description: "Haptic Toggle" },
            { keycode: "HPT_RST", description: "Haptic Reset" },
            { keycode: "HPT_FBK", description: "Haptic Feedback" },
            { keycode: "HPT_BUZ", description: "Haptic Buzz" },
            { keycode: "HPT_MODI", description: "Haptic Mode Increase" },
            { keycode: "HPT_MODD", description: "Haptic Mode Decrease" },
            { keycode: "HPT_CONT", description: "Haptic Continuous" },
            { keycode: "HPT_CONI", description: "Haptic Continuous Increase" },
            { keycode: "HPT_COND", description: "Haptic Continuous Decrease" },
            { keycode: "HPT_DWLI", description: "Haptic Dwell Increase" },
            { keycode: "HPT_DWLD", description: "Haptic Dwell Decrease" },
        ],
    },
    {
        name: "Auto-Shift",
        description: "Auto-shift feature controls",
        keys: [
            { keycode: "KC_ASDN", description: "Auto-Shift Timeout Down" },
            { keycode: "KC_ASUP", description: "Auto-Shift Timeout Up" },
            { keycode: "KC_ASRP", description: "Auto-Shift Report" },
            { keycode: "KC_ASON", description: "Auto-Shift On" },
            { keycode: "KC_ASOFF", description: "Auto-Shift Off" },
            { keycode: "KC_ASTG", description: "Auto-Shift Toggle" },
        ],
    },
    {
        name: "Combo Toggle",
        description: "Combo feature controls",
        keys: [
            { keycode: "CMB_ON", description: "Combos On" },
            { keycode: "CMB_OFF", description: "Combos Off" },
            { keycode: "CMB_TOG", description: "Combos Toggle" },
        ],
    },
    {
        name: "Steno",
        description: "Stenography keys",
        keys: [
            { keycode: "QK_STENO_BOLT", description: "Steno Bolt" },
            { keycode: "QK_STENO_GEMINI", description: "Steno Gemini" },
            { keycode: "STN_NUM", description: "Steno Num Bar" },
            { keycode: "STN_S1", description: "Steno S1" },
            { keycode: "STN_S2", description: "Steno S2" },
            { keycode: "STN_TL", description: "Steno T Left" },
            { keycode: "STN_KL", description: "Steno K Left" },
            { keycode: "STN_PL", description: "Steno P Left" },
            { keycode: "STN_WL", description: "Steno W Left" },
            { keycode: "STN_HL", description: "Steno H Left" },
            { keycode: "STN_RL", description: "Steno R Left" },
            { keycode: "STN_A", description: "Steno A" },
            { keycode: "STN_O", description: "Steno O" },
            { keycode: "STN_E", description: "Steno E" },
            { keycode: "STN_U", description: "Steno U" },
            { keycode: "STN_ST1", description: "Steno Star 1" },
            { keycode: "STN_ST2", description: "Steno Star 2" },
            { keycode: "STN_ST3", description: "Steno Star 3" },
            { keycode: "STN_ST4", description: "Steno Star 4" },
            { keycode: "STN_FR", description: "Steno F Right" },
            { keycode: "STN_RR", description: "Steno R Right" },
            { keycode: "STN_PR", description: "Steno P Right" },
            { keycode: "STN_BR", description: "Steno B Right" },
            { keycode: "STN_LR", description: "Steno L Right" },
            { keycode: "STN_GR", description: "Steno G Right" },
            { keycode: "STN_TR", description: "Steno T Right" },
            { keycode: "STN_SR", description: "Steno S Right" },
            { keycode: "STN_DR", description: "Steno D Right" },
            { keycode: "STN_ZR", description: "Steno Z Right" },
            { keycode: "STN_RES1", description: "Steno Reset 1" },
            { keycode: "STN_RES2", description: "Steno Reset 2" },
            { keycode: "STN_PWR", description: "Steno Power" },
        ],
    },
    {
        name: "International",
        description: "International keyboard keys",
        keys: [
            { keycode: "KC_RO", description: "Ro (Japanese)" },
            { keycode: "KC_KANA", description: "Kana (Japanese)" },
            { keycode: "KC_JYEN", description: "Yen (Japanese)" },
            { keycode: "KC_HENK", description: "Henkan (Japanese)" },
            { keycode: "KC_MHEN", description: "Muhenkan (Japanese)" },
            { keycode: "KC_LANG1", description: "Language 1 (Korean)" },
            { keycode: "KC_LANG2", description: "Language 2 (Korean)" },
        ],
    },
    {
        name: "Lock Keys",
        description: "Lock and toggle keys",
        keys: [
            { keycode: "KC_LCAP", description: "Locking Caps" },
            { keycode: "KC_LNUM", description: "Locking Num" },
            { keycode: "KC_LSCR", description: "Locking Scroll" },
        ],
    },
    {
        name: "Editing Commands",
        description: "Common editing command keys",
        keys: [
            { keycode: "KC_UNDO", description: "Undo" },
            { keycode: "KC_REDO", description: "Redo" },
            { keycode: "KC_CUT", description: "Cut" },
            { keycode: "KC_COPY", description: "Copy" },
            { keycode: "KC_PSTE", description: "Paste" },
            { keycode: "KC_FIND", description: "Find" },
            { keycode: "KC_SLCT", description: "Select" },
            { keycode: "KC_EXEC", description: "Execute" },
            { keycode: "KC_HELP", description: "Help" },
            { keycode: "KC_MENU", description: "Menu" },
            { keycode: "KC_STOP", description: "Stop" },
        ],
    },
    {
        name: "QMK Magic",
        description: "QMK Magic key swap/toggle controls",
        keys: [
            { keycode: "QK_MAGIC_TOGGLE_CONTROL_CAPS_LOCK", description: "Toggle Ctrl/CapsLock swap" },
            { keycode: "QK_MAGIC_TOGGLE_GUI", description: "Toggle GUI disable" },
            { keycode: "QK_MAGIC_TOGGLE_BACKSLASH_BACKSPACE", description: "Toggle Backslash/Backspace swap" },
            { keycode: "QK_MAGIC_SWAP_ESCAPE_CAPS_LOCK", description: "Swap Esc/CapsLock" },
            { keycode: "QK_MAGIC_UNSWAP_ESCAPE_CAPS_LOCK", description: "Unswap Esc/CapsLock" },
            { keycode: "QK_MAGIC_TOGGLE_ESCAPE_CAPS_LOCK", description: "Toggle Esc/CapsLock swap" },
        ],
    },
];

/**
 * Get KeyContent for a keycode using the mock keyboard info
 */
export function getProofKeyContents(keycode: string): KeyContent | undefined {
    return getKeyContents(mockKeyboardInfo, keycode);
}
