import React from 'react';
import { SVALBOARD_LAYOUT } from '@/constants/svalboard-layout';
import { printService, type PrintableLayer } from '@/services/print.service';
import { getKeyLabel } from '@/utils/layers';
import type { KeyboardInfo } from '@/types/vial.types';
import './PrintableKeymap.css';

interface PrintableKeymapProps {
  keyboard: KeyboardInfo;
  layers: PrintableLayer[];
}

// Smaller unit size for print (fits better on paper)
const PRINT_UNIT_SIZE = 36;

/**
 * A print-optimized keyboard layout that shows all non-empty layers
 * This component is hidden on screen but visible when printing
 */
export const PrintableKeymap: React.FC<PrintableKeymapProps> = ({ keyboard, layers }) => {
  // Calculate keyboard dimensions
  let maxX = 0;
  let maxY = 0;
  Object.values(SVALBOARD_LAYOUT).forEach((key) => {
    maxX = Math.max(maxX, key.x + key.w);
    maxY = Math.max(maxY, key.y + key.h);
  });

  const keyboardWidth = maxX * PRINT_UNIT_SIZE;
  const keyboardHeight = maxY * PRINT_UNIT_SIZE;

  return (
    <div className="printable-keymap-container">
      {/* Header with keyboard info */}
      <div className="print-header">
        <h1 className="print-title">
          {keyboard.cosmetic?.name || keyboard.name || 'Keyboard Layout'}
        </h1>
        <p className="print-subtitle">
          {layers.length} layer{layers.length !== 1 ? 's' : ''} with configured keys
        </p>
      </div>

      {/* Render each non-empty layer */}
      {layers.map((layer, layerIdx) => (
        <div key={layer.index} className="print-layer" style={{ pageBreakInside: 'avoid' }}>
          <div className="print-layer-header">
            <span className="print-layer-index">{layer.index}</span>
            <span className="print-layer-name">{layer.name}</span>
          </div>

          <div
            className="print-keyboard-layout"
            style={{ width: `${keyboardWidth}px`, height: `${keyboardHeight}px` }}
          >
            {Object.entries(SVALBOARD_LAYOUT).map(([matrixPos, layout]) => {
              const pos = Number(matrixPos);
              const keycode = layer.keymap[pos] || 0;
              const { text, isEmpty } = printService.getKeycodeDisplay(keycode);

              // Get label from keyboard info for better display
              const { label: kbLabel } = getKeyLabel(keyboard, keycode);
              const displayText = kbLabel && kbLabel !== 'KC_NO' ? kbLabel : text;

              const style: React.CSSProperties = {
                left: `${layout.x * PRINT_UNIT_SIZE}px`,
                top: `${layout.y * PRINT_UNIT_SIZE}px`,
                width: `${layout.w * PRINT_UNIT_SIZE}px`,
                height: `${layout.h * PRINT_UNIT_SIZE}px`,
              };

              return (
                <div
                  key={matrixPos}
                  className={`print-key ${isEmpty ? 'print-key-empty' : ''}`}
                  style={style}
                >
                  <span className="print-key-label">{displayText}</span>
                </div>
              );
            })}
          </div>

          {/* Add page break after every 2 layers except the last */}
          {layerIdx % 2 === 1 && layerIdx < layers.length - 1 && (
            <div className="print-page-break" />
          )}
        </div>
      ))}

      {/* Footer */}
      <div className="print-footer">
        <p>Generated by KeyBard</p>
      </div>
    </div>
  );
};

export default PrintableKeymap;
